#!/usr/bin/env python3
"""RIoT2 documentation drift check.

Checks the documentation of every repository in a RIoT2 workspace (a folder that holds `.github`
and the `RIoT2.*` repositories side by side) for broken links, layout violations, leaked local
values, and drift between the platform contracts in `.github/docs/contracts` and the code.

Usage (from the workspace root):
    python .github/tools/docs-check/check_docs.py [--workspace PATH] [--only CHECK[,CHECK]]
                                                  [--warnings-as-errors] [--list]

Exit code 1 when any ERROR is reported. Standard library only (Python 3.9+).
See README.md next to this file for what each check enforces.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

ORG = "Revolutionized-IoT2"
SKIP_DIRS = {".git", ".pio", "node_modules", "bin", "obj", "dist", "TestResults", ".vs", ".vscode",
             ".host-build", "__pycache__", "packages", ".localfeed"}
# Scaffold READMEs generated by the Vuetify template; not part of the documentation set.
SKIP_DOC_PREFIXES = ("RIoT2.Matter/Controller/Ui/src/",)
SIZE_WARN, SIZE_ERROR = 15_500, 20_000
REQUIRED_AGENTS_SECTIONS = ["## What this is", "## Commands", "## Layout", "## Rules", "## Pitfalls", "## Related work"]
COPILOT_POINTER = "Follow [AGENTS.md](../AGENTS.md)"
STALE_TEXT = re.compile(r"(?i)continuation plan|hand-?off baseline|resuming this work|\b\d+/\d+ passed\b")
PLANNED = "Planned (not implemented)"
# Test projects and fixtures are not product code: Tests/, tests/, RIoT2.X.Tests/, *.test.*, *Tests.cs, MockUps/.
TEST_PATH = re.compile(r"(?i)[\\/](tests?|[\w.]+\.tests|mockups)[\\/]|\.test\.|tests?\.cs$")


@dataclass
class Finding:
    level: str
    check: str
    where: str
    message: str


@dataclass
class Context:
    ws: Path
    repos: dict[str, Path]
    findings: list[Finding] = field(default_factory=list)
    _anchors: dict[Path, set[str]] = field(default_factory=dict)

    def error(self, check, where, msg): self.findings.append(Finding("ERROR", check, str(where), msg))
    def warn(self, check, where, msg): self.findings.append(Finding("WARN", check, str(where), msg))

    def rel(self, p: Path) -> str:
        try:
            return p.resolve().relative_to(self.ws).as_posix()
        except ValueError:
            return p.as_posix()

    def anchors(self, p: Path) -> set[str]:
        if p not in self._anchors:
            text = strip_code(read(p))
            found = {slug(m.group(1)) for m in re.finditer(r"^#{1,6}\s+(.*?)\s*#*\s*$", text, re.M)}
            found |= set(re.findall(r'<a\s+(?:id|name)="([^"]+)"', text))
            self._anchors[p] = found
        return self._anchors[p]

    def hub(self) -> Path:
        return self.ws / ".github"

    def contract(self, name: str) -> Path:
        return self.hub() / "docs" / "contracts" / name


def read(p: Path) -> str:
    return p.read_text(encoding="utf-8-sig", errors="replace")


def strip_code(text: str) -> str:
    return re.sub(r"```.*?```", "", text, flags=re.S)


def slug(heading: str) -> str:
    h = re.sub(r"`|\*\*|\[|\]\([^)]*\)", "", heading.strip().lower())
    return re.sub(r"[^\w\- ]", "", h).replace(" ", "-")


def walk(root: Path, suffixes: tuple[str, ...]):
    for d, dirs, files in os.walk(root):
        dirs[:] = [x for x in dirs if x not in SKIP_DIRS]
        for f in files:
            if f.endswith(suffixes):
                yield Path(d) / f


def doc_files(ctx: Context, repo: Path):
    for p in walk(repo, (".md",)):
        if not ctx.rel(p).startswith(SKIP_DOC_PREFIXES):
            yield p


def default_branch(repo: Path) -> str:
    for args in (["symbolic-ref", "--short", "refs/remotes/origin/HEAD"], ["branch", "--show-current"]):
        try:
            out = subprocess.run(["git", "-C", str(repo), *args], capture_output=True, text=True, timeout=10).stdout.strip()
        except (OSError, subprocess.SubprocessError):
            out = ""
        if out:
            return out.split("/")[-1]
    return "main"


def section(text: str, heading: str) -> str:
    """Body of the first section whose heading starts with `heading` (until a same-or-higher heading)."""
    m = re.search(rf"^(#+)\s+{re.escape(heading)}.*$", text, re.M)
    if not m:
        return ""
    rest = text[m.end():]
    end = re.search(rf"^#{{1,{len(m.group(1))}}}\s", rest, re.M)
    return rest[: end.start()] if end else rest


def without_sections(text: str, headings: tuple[str, ...]) -> str:
    for h in headings:
        body = section(text, h)
        if body:
            text = text.replace(body, "")
    return text


# -------------------------------------------------------------------------------------- 1. links
def check_links(ctx: Context):
    """Relative links, anchors and links to other RIoT2 repositories (resolved in the workspace)."""
    branches = {name: default_branch(path) for name, path in ctx.repos.items()}
    gh = re.compile(rf"https://github\.com/{ORG}/([\w.\-]+)(?:/(blob|tree)/([\w.\-]+)/?([^)#\s]*))?(?:#([^)\s]+))?$")
    for repo in ctx.repos.values():
        for doc in doc_files(ctx, repo):
            body = re.sub(r"`[^`\n]*`", "", strip_code(read(doc)))
            for m in re.finditer(r"\]\(\s*<?([^)\s>]+)>?(?:\s+\"[^\"]*\")?\s*\)", body):
                target = m.group(1)
                g = gh.match(target)
                if g:
                    repo_name, kind, branch, path, anchor = g.groups()
                    if repo_name not in ctx.repos:
                        continue  # repository not checked out; nothing to resolve against
                    if kind and branch != branches[repo_name]:
                        ctx.error("links", ctx.rel(doc), f"{target}: branch '{branch}', but {repo_name} uses '{branches[repo_name]}'")
                    if not kind:
                        continue
                    local = ctx.repos[repo_name] / path
                elif re.match(r"^[a-z][\w+.-]*:", target):
                    continue  # other external URL
                else:
                    path, _, anchor = target.partition("#")
                    local = (doc.parent / path).resolve() if path else doc
                if not local.exists():
                    ctx.error("links", ctx.rel(doc), f"broken link: {target}")
                elif anchor and local.suffix == ".md" and anchor not in ctx.anchors(local):
                    ctx.error("links", ctx.rel(doc), f"missing anchor: {target}")


# ------------------------------------------------------------------------------------- 2. images
def check_images(ctx: Context):
    """Every image in the hub is used by a document (obsolete screenshots get deleted)."""
    hub = ctx.hub()
    referenced: set[Path] = set()
    for doc in doc_files(ctx, hub):
        for m in re.finditer(r"!\[[^\]]*\]\(([^)\s]+)\)", strip_code(read(doc))):
            if not re.match(r"^[a-z]+:", m.group(1)):
                referenced.add((doc.parent / m.group(1)).resolve())
    for img in walk(hub, (".png", ".jpg", ".jpeg", ".gif", ".svg", ".webp")):
        if img.resolve() not in referenced:
            ctx.error("images", ctx.rel(img), "image is not referenced by any document; use it or delete it")


# --------------------------------------------------------------------------------------- 3. size
def check_size(ctx: Context):
    """Documents stay under ~15 KB (warning) and 20 KB (error); CHANGELOG.md is exempt."""
    for repo in ctx.repos.values():
        for doc in doc_files(ctx, repo):
            if doc.name == "CHANGELOG.md":
                continue
            size = doc.stat().st_size
            if size > SIZE_ERROR:
                ctx.error("size", ctx.rel(doc), f"{size} bytes; split it (AI tools read about 20 KB at a time)")
            elif size > SIZE_WARN:
                ctx.warn("size", ctx.rel(doc), f"{size} bytes; keep documents under about 15 KB")


# ------------------------------------------------------------------------------------- 4. layout
def check_layout(ctx: Context):
    """Per-repository file set from ADR 0001."""
    for name, repo in ctx.repos.items():
        if name == ".github":
            continue
        for required in ("README.md", "AGENTS.md", "CLAUDE.md", "CHANGELOG.md"):
            if not (repo / required).exists():
                ctx.error("layout", name, f"missing {required}")
        if (repo / ".github" / "upgrades").exists():
            ctx.error("layout", name, ".github/upgrades is stale upgrade-assistant output; delete it")
        agents = repo / "AGENTS.md"
        if agents.exists():
            text = read(agents)
            missing = [s for s in REQUIRED_AGENTS_SECTIONS if s not in text]
            if missing:
                ctx.error("layout", ctx.rel(agents), f"missing sections: {', '.join(missing)}")
            if f"{ORG}/.github/blob/main/AGENTS.md" not in text:
                ctx.error("layout", ctx.rel(agents), "must point to the hub AGENTS.md")
        changelog = repo / "CHANGELOG.md"
        if changelog.exists() and "## [Unreleased]" not in read(changelog):
            ctx.error("layout", ctx.rel(changelog), "missing '## [Unreleased]'")
        for doc in doc_files(ctx, repo):
            text = read(doc)
            if doc.name == "CLAUDE.md":
                if text.strip() != "@AGENTS.md":
                    ctx.error("layout", ctx.rel(doc), "CLAUDE.md must contain only '@AGENTS.md'")
                if not (doc.parent / "AGENTS.md").exists():
                    ctx.error("layout", ctx.rel(doc), "CLAUDE.md has no sibling AGENTS.md")
            if doc.name == "copilot-instructions.md" and COPILOT_POINTER not in text:
                ctx.error("layout", ctx.rel(doc), "copilot-instructions.md must only point to AGENTS.md")
            if doc.name in ("README.md", "AGENTS.md"):
                m = STALE_TEXT.search(text)
                if m:
                    ctx.error("layout", ctx.rel(doc), f"session hand-off or test-count text '{m.group(0)}' (use issues or PRs)")


# ------------------------------------------------------------------------------------ 5. secrets
def check_secrets(ctx: Context):
    """Values from local settings files (launchSettings*, appsettings*) must not appear in docs."""
    values: dict[str, str] = {}
    key_rx = re.compile(r"(?i)(_ID|PASSWORD|TOKEN|SECRET|KEY)$")
    for repo in ctx.repos.values():
        for p in walk(repo, (".json",)):
            if not re.match(r"(?i)(launchSettings.*|appsettings.*)\.json$", p.name):
                continue
            try:
                data = json.loads(re.sub(r"(?m)^\s*//.*$|(?<=[,\"\d])\s*//.*$", "", read(p)))
            except ValueError:
                continue
            stack = [data]
            while stack:
                cur = stack.pop()
                items = cur.items() if isinstance(cur, dict) else enumerate(cur) if isinstance(cur, list) else []
                for k, v in items:
                    if isinstance(v, (dict, list)):
                        stack.append(v)
                    elif (isinstance(v, str) and isinstance(k, str) and key_rx.search(k) and len(v) >= 8
                          and not re.search(r"(?i)localhost|example|<|dev-", v)
                          and not re.fullmatch(r"[a-z]+", v)):  # plain words such as "password" are not secrets
                        values[v] = f"{ctx.rel(p)} ({k})"
    for repo in ctx.repos.values():
        for doc in doc_files(ctx, repo):
            text = read(doc)
            for value, origin in values.items():
                if value in text:
                    ctx.error("secrets", ctx.rel(doc), f"contains the value of {origin}; use a placeholder")


# ------------------------------------------------------------------------ 6. contract: MQTT topics
def check_mqtt(ctx: Context):
    """Topic templates in Constants.cs, the firmware Topics.h and mqtt-topics.md are the same set."""
    core = ctx.ws / "RIoT2.Core" / "Constants.cs"
    shared = ctx.ws / "RIoT2.Ard.Shared" / "RIoT2Shared" / "include" / "riot2" / "Topics.h"
    doc = ctx.contract("mqtt-topics.md")
    if not core.exists():
        return ctx.warn("mqtt", "workspace", "RIoT2.Core not checked out; skipped")
    code = set(re.findall(r'"(riot2/[^"]+)"', read(core)))
    documented = set(re.findall(r"`(riot2/[^`]+)`", section(read(doc), "Topics")))
    for t in sorted(code - documented):
        ctx.error("mqtt", ctx.rel(doc), f"topic {t} (RIoT2.Core/Constants.cs) is missing from the Topics table")
    for t in sorted(documented - code):
        ctx.error("mqtt", ctx.rel(doc), f"topic {t} is in the Topics table but not in RIoT2.Core/Constants.cs")
    if shared.exists():
        h = read(shared)
        fw = {f"riot2/node/{{id}}/{m}" for m in re.findall(r'"riot2/node/"\s*\+\s*\w+\s*\+\s*"/(\w+)"', h)}
        fw |= set(re.findall(r'"(riot2/orchestrator/[^"]+)"', h))
        for t in sorted(code ^ fw):
            ctx.error("mqtt", ctx.rel(shared), f"firmware topics differ from RIoT2.Core/Constants.cs: {t}")


# ------------------------------------------------------------------------------- 7. contract: enums
def check_enums(ctx: Context):
    """Numeric enum values are wire format; the contract docs must state them."""
    enums_cs = ctx.ws / "RIoT2.Core" / "Enums.cs"
    if not enums_cs.exists():
        return
    text = read(enums_cs)
    targets = {"MqttTopic": ["mqtt-topics.md"], "NodeType": ["mqtt-topics.md"],
               "ValueType": ["mqtt-topics.md", "configuration.md"]}
    for enum, docs in targets.items():
        m = re.search(rf"enum\s+{enum}\s*\{{(.*?)\}}", text, re.S)
        if not m:
            ctx.error("enums", ctx.rel(enums_cs), f"enum {enum} not found")
            continue
        members = re.findall(r"(\w+)\s*=\s*(\d+)", re.sub(r"//.*", "", m.group(1)))
        for d in docs:
            body = read(ctx.contract(d))
            for name, value in members:
                if not any(f in body for f in (f"`{name}` ({value})", f"{name}` ({value})", f"`{value}` {name}")):
                    ctx.error("enums", ctx.rel(ctx.contract(d)),
                              f"{enum}.{name} = {value} is not documented as \"`{name}` ({value})\" or \"`{value}` {name}\"")


# ---------------------------------------------------------------------------- 8. contract: env vars
# Repositories whose code reads the documented variables; all must be present to flag unused ones.
ENV_REPOS = ("RIoT2.Net.Orchestrator", "RIoT2.Net.Node", "RIoT2.Elsa", "RIoT2.Connector.InfluxDB", "RIoT2.UI")
ENV_RX = re.compile(r"\b((?:RIOT2|VITE_MQTT|ELSA)_[A-Z0-9_]+)\b")


def check_env(ctx: Context):
    """Every RIOT2_/VITE_MQTT_/ELSA_ variable read by code is in env-vars.md, and vice versa."""
    doc = ctx.contract("env-vars.md")
    code: dict[str, str] = {}
    for name, repo in ctx.repos.items():
        if name == ".github":
            continue
        for p in walk(repo, (".cs", ".ts", ".sh", ".js")):
            if TEST_PATH.search(str(p)) or re.search(r"(?i)vite\.config|\.d\.ts$", str(p)):
                continue
            for v in ENV_RX.findall(read(p)):
                code.setdefault(v, ctx.rel(p))
        for p in repo.glob("Dockerfile*"):
            for v in re.findall(r"^\s*ENV\s+((?:RIOT2|VITE_MQTT|ELSA)_[A-Z0-9_]+)", read(p), re.M):
                code.setdefault(v, ctx.rel(p))
    text = read(doc)
    current = set(ENV_RX.findall(without_sections(text, (PLANNED,))))
    planned = set(ENV_RX.findall(section(text, PLANNED)))
    for v in sorted(set(code) - current - planned):
        ctx.error("env", ctx.rel(doc), f"{v} is read by {code[v]} but not documented")
    absent = [r for r in ENV_REPOS if r not in ctx.repos]
    if absent:
        ctx.warn("env", ctx.rel(doc), f"documented-but-unused check skipped; not checked out: {', '.join(absent)}")
    else:
        for v in sorted(current - set(code)):
            ctx.error("env", ctx.rel(doc), f"{v} is documented as current but no code reads it (move it under '{PLANNED}' or remove it)")
    for v in sorted(planned & set(code)):
        ctx.warn("env", ctx.rel(doc), f"{v} is listed as planned, but {code[v]} already reads it")


# ------------------------------------------------------------------------------ 9. contract: routes
# An attribute such as [Route("api/[controller]")] can contain one level of nested brackets.
ATTR = r"\[(?:[^\[\]]|\[[^\]]*\])*\]"
ROUTE_REPOS = ("RIoT2.Net.Orchestrator", "RIoT2.Net.Node", "RIoT2.Net.Devices", "RIoT2.Elsa", "RIoT2.Connector.InfluxDB")


def norm_route(r: str) -> str:
    return re.sub(r"\{[^}]*\}", "{}", "/" + r.strip().strip("/").lower())


def code_routes(ctx: Context) -> dict[str, str]:
    routes: dict[str, str] = {}
    for name in ROUTE_REPOS:
        repo = ctx.repos.get(name)
        if not repo:
            continue
        for p in walk(repo, (".cs",)):
            if TEST_PATH.search(str(p)):
                continue
            text = read(p)
            cls = re.search(rf'((?:{ATTR}\s*)*)public\s+(?:sealed\s+|partial\s+)*class\s+(\w+)Controller\b', text)
            if cls:
                base_m = re.search(r'\[Route\("([^"]+)"\)\]', cls.group(1))
                base = base_m.group(1).replace("[controller]", cls.group(2).lower()) if base_m else ""
                for attrs in re.findall(rf"((?:{ATTR}\s*)+)public\s+[^(;={{]+\(", text[cls.end():]):
                    route = re.search(r'\[Route\("([^"]*)"\)\]', attrs)
                    # A method can carry several [HttpX] attributes, one per route.
                    for verb_arg in re.findall(r'\[Http(?:Get|Post|Put|Delete|Patch)(?:\("([^"]*)"\))?\]', attrs):
                        sub = verb_arg or (route.group(1) if route else "")
                        routes[norm_route(f"{base}/{sub}")] = ctx.rel(p)
            groups = dict(re.findall(r'(\w+)\s*=\s*\w+\.MapGroup\("([^"]+)"\)', text))
            for target, path in re.findall(r'(\w+)\.Map(?:Get|Post|Put|Delete|HealthChecks)\("([^"]+)"', text):
                routes[norm_route(groups.get(target, "") + path)] = ctx.rel(p)
    return routes


def check_routes(ctx: Context):
    """Every HTTP endpoint mapped in code is in http-api.md; documented ones should exist (warning)."""
    doc = ctx.contract("http-api.md")
    text = read(doc)
    documented = {norm_route(r) for r in re.findall(r"`(?:(?:GET|POST|PUT|DELETE)\s+)?(?:\{[^}`]*\})?(/[\w{}/.\-]+)", text)}
    found = code_routes(ctx)
    for route, where in sorted(found.items()):
        if route not in documented:
            ctx.error("routes", ctx.rel(doc), f"endpoint {route} ({where}) is not documented")
    absent = [r for r in ROUTE_REPOS if r not in ctx.repos]
    if absent:
        return ctx.warn("routes", ctx.rel(doc), f"documented-endpoint check skipped; not checked out: {', '.join(absent)}")
    current = without_sections(text, (PLANNED, "Firmware"))
    for r in sorted({norm_route(x) for x in re.findall(r"\|\s*(?:GET|POST|PUT|DELETE)[^|]*\|\s*`(/api/[^`]+)`", current)}):
        if r not in found:
            ctx.warn("routes", ctx.rel(doc), f"documented endpoint {r} was not found in code")


# ------------------------------------------------------------------------------- 10. contract: proto
def proto_shape(p: Path) -> str:
    t = re.sub(r"//.*", "", read(p))
    t = re.sub(r"^\s*option\s+csharp_namespace.*$", "", t, flags=re.M)
    return re.sub(r"\s+", " ", t).strip()


def check_proto(ctx: Context):
    """Orchestrator and Elsa .proto files define the same contract (csharp_namespace may differ)."""
    a = ctx.ws / "RIoT2.Net.Orchestrator" / "Protos" / "riot_trigger.proto"
    b = ctx.ws / "RIoT2.Elsa" / "RIoT2.Elsa.Server" / "RIoT" / "Protos" / "riot.proto"
    if a.exists() and b.exists() and proto_shape(a) != proto_shape(b):
        ctx.error("proto", ctx.rel(a), f"gRPC contract differs from {ctx.rel(b)} (only csharp_namespace may differ)")


# ------------------------------------------------------------------------ 11. hub code references
def check_code_refs(ctx: Context):
    """`RIoT2.X/path.ext` references in current-state hub docs must exist (when the repo is present)."""
    rx = re.compile(r"`(RIoT2\.[\w.]+)/([\w./\-]+\.(?:cs|h|cpp|ts|vue|proto|json|sh|ini|yml|md))`")
    for doc in doc_files(ctx, ctx.hub()):
        if {"reviews", "design", "plans", "backlog"} & set(doc.parts):
            continue  # snapshots may describe code that has changed since
        for repo_name, path in sorted(set(rx.findall(read(doc)))):
            repo = ctx.repos.get(repo_name)
            if repo and not (repo / path).exists():
                ctx.error("coderefs", ctx.rel(doc), f"`{repo_name}/{path}` does not exist")


CHECKS = {
    "links": check_links, "images": check_images, "size": check_size, "layout": check_layout,
    "secrets": check_secrets, "mqtt": check_mqtt, "enums": check_enums, "env": check_env,
    "routes": check_routes, "proto": check_proto, "coderefs": check_code_refs,
}
CONTRACT_CHECKS = {"mqtt", "enums", "env", "routes", "proto", "coderefs"}


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="RIoT2 documentation drift check")
    ap.add_argument("--workspace", default=str(Path(__file__).resolve().parents[3]),
                    help="folder that contains .github and the RIoT2.* repositories (default: inferred)")
    ap.add_argument("--only", help="comma-separated subset of: " + ",".join(CHECKS))
    ap.add_argument("--warnings-as-errors", action="store_true")
    ap.add_argument("--list", action="store_true", help="list the checks and exit")
    args = ap.parse_args(argv)
    if args.list:
        for name, fn in CHECKS.items():
            print(f"{name:9} {(fn.__doc__ or '').strip().splitlines()[0] if fn.__doc__ else ''}")
        return 0
    ws = Path(args.workspace).resolve()
    if not (ws / ".github").is_dir():
        print(f"error: {ws} does not contain the .github hub", file=sys.stderr)
        return 2
    repos = {".github": ws / ".github"}
    repos.update({p.name: p for p in sorted(ws.iterdir()) if p.is_dir() and p.name.startswith("RIoT2.")})
    selected = args.only.split(",") if args.only else list(CHECKS)
    unknown = [s for s in selected if s not in CHECKS]
    if unknown:
        print(f"error: unknown check(s): {', '.join(unknown)}", file=sys.stderr)
        return 2
    missing_code = len(repos) == 1 and CONTRACT_CHECKS & set(selected)
    if missing_code:
        print("note: no RIoT2.* repositories next to .github; contract checks have nothing to compare", file=sys.stderr)
    ctx = Context(ws, repos)
    for name in selected:
        CHECKS[name](ctx)
    for f in sorted(ctx.findings, key=lambda f: (f.level != "ERROR", f.check, f.where, f.message)):
        print(f"{f.level:5} [{f.check}] {f.where}: {f.message}")
    n_err = sum(f.level == "ERROR" for f in ctx.findings)
    n_warn = sum(f.level == "WARN" for f in ctx.findings)
    print(f"\n{len(repos)} repositories; checks: {', '.join(selected)}; {n_err} errors, {n_warn} warnings")
    return 1 if n_err or (args.warnings_as_errors and n_warn) else 0


if __name__ == "__main__":
    sys.exit(main())
